### ISSUE TITLE
Action Crud\Action\DeleteAction does not implement a handler for HTTP verb _get

### ISSUE THREAD

**Issue by ajayvavdiya** [cakephp/cakephp#11597]
![delete_record](https://user-images.githubusercontent.com/26171170/34496974-9e52ce72-f021-11e7-9508-bb6284c36551.png)

![showrecord](https://user-images.githubusercontent.com/26171170/34496962-978494d6-f021-11e7-8382-8ba37e9edbe5.png)
* [x] bug

* CakePHP Version: 3.5
Windows Platform 

### What you did
I Want To delete record. I am working on crud latest version crud 5.2, crud-view plugin. all method working but only delete not working.
![crud_error](https://user-images.githubusercontent.com/26171170/34496898-60356f64-f021-11e7-9bc0-bbafef596e09.png)

### What happened
i want remove record but not working.

### What you expected to happen
remove record

Is this any kind of plugins error?

**Comment by markstory** [comment]
Sounds like this is an issue with [the crud plugin](https://github.com/FriendsOfCake/crud) and not CakePHP.

**Comment by ajayvavdiya** [comment]
How can we solved this plugin error? @markstory @ADmad

**Comment by ADmad** [comment]
Delete actions aren't supposed to be called using GET. Use `FormHelper::postLink()` to generate your delete links.

**Comment by ajayvavdiya** [comment]
Thank you

**Comment by VARGA-Peter** [comment]
@ADmad  **Thank you very much for your time and that you helped even it isn't really a CakePHP issue**. @markstory likes to close the issues, you rather help.

I did the same mistake like @ajayvavdiya and without your hint I would have spent probably 3 more hours until I would have fix my mistake!
