### ISSUE TITLE
[3.5.18] preg_match Regex in SqlDialectTrait wrong for PHP>=7.3

### ISSUE THREAD

**Issue by Manuel1948** [cakephp/cakephp#16269]
### Description

I get many warnings in the error.log:
2022-01-28 13:22:33 Warning: Warning (2): preg_match() [<a href='https://secure.php.net/function.preg-match'>function.preg-match</a>]: Compilation failed: invalid range in character class at offset 4 in [/xxx/src/Database/SqlDialectTrait.php, line 71]

And in this file on line 71 there is this code:
`if (preg_match('/^[\w-_\s]*[\w-_]+/', $identifier)) {`

So if I check this regex on regex101.com for PCRE2 there is an error because you have to escape the dashes, correect line would be:
`if (preg_match('/^[\w\-_\s]*[\w\-_]+/', $identifier)) {`

Maybe CakePHP 3.5 is maximum working with PHP 7.3 (and not PHP 7.4 like on this page: https://book.cakephp.org/3/en/index.html ), I saw many other errors, like on implode-functions (because in PHP 7.4 they changed the order of the parameters)

### CakePHP Version

3.5.18

### PHP Version

7.4

**Comment by dereuromark** [comment]
Same as https://github.com/cakephp/cakephp/issues/16270#issuecomment-1024191633
When using more modern PHP versions always respect min versions as per minor updates according to the tested ones.
